first_project/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    

]

my_app/urls.py
from django.contrib import admin
from django.urls import path 
from my_app import views

app_name = "my_app"

urlpatterns = [
    path('', views.home, name="home"),
    path('form/', views.form, name="form"),
    
]

my_app/models.py
from django.db import models

# Create your models here.

class students(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    dept = models.CharField(max_length=50)

    def __str__(self):
        return self.name + " " + self.dept 
    

my_app/forms.py
from django import forms
from my_app import models

class StudentForm(forms.ModelForm):
    class Meta:
        model = models.students
        fields = "__all__"

my_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import students 
from my_app import forms


# Create your views here.

def home(request):
    students_list = students.objects.order_by('name')
    diction = {'students': students_list}
    return render(request, 'my_app/index.html', context=diction)
   

def form(request):
    new_form = forms.StudentForm()

    if request.method == "POST":
        new_form = forms.StudentForm(request.POST)

        if new_form.is_valid():
            new_form.save(commit=True)
            return home(request)

    diction = {'test_form': new_form}
    return render(request, 'my_app/form.html', context=diction)

templates/my_app/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {{ test_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>

    <a href="{% url 'my_app:home' %}">Back</a> 
</body>
</html>

templates/my_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>

    <table border="1">
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Depatment</th>
        </tr>

        {% for row in students %}

        <tr>
            <td>{{ row.name }}</td>
            <td>{{ row.age }}</td>
            <td>{{ row.dept }}</td>
        </tr>

        {% endfor %}

    </table>

    <a href="{% url 'my_app:form' %}">Add new</a>

</body>
</html>